### ISSUE TITLE
fix multiple modal overlays

### ISSUE THREAD

**Issue by cwaring** [ipfs-shipyard/ipfs-thing-2023#59]
https://user-images.githubusercontent.com/106938/229758841-fb99dee3-268d-4515-8ccf-224b024d0e5b.mp4

**Comment by Frando** [comment]
Also it seems:
* Scrolling is broken and for the long overlays it's impossible to read the text
* Text selection / copy paste does not work - I had to resort to "view source" to copy-paste my talk description into an email

**Comment by cwaring** [comment]
@Frando both of these issues for the modal overlay should now be fixed in #61
